class Butterfly():
    butterfly_data = [
        {
            "Common Name": "Adonis",
            "Binomial Name": "Polyommatus bellargus",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Lycaenidae",
            "Genus": "Polyommatus",
            "Species": "P. bellargus"
        },
        {
            "Common Name": "American Snoot",
            "Binomial Name": "Libytheana carinenta",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Nymphalidae",
            "Genus": "Libytheana",
            "Species": "L. carinenta"
        },
        {
            "Common Name": "An 88",
            "Binomial Name": "Diaethria anna",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Nymphalidae",
            "Genus": "Diaethria",
            "Species": "D. anna"
        },
        {
            "Common Name": "Banded Peacock Butterfly",
            "Binomial Name": "Papilio crino",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Papilionidae",
            "Genus": "Papilio",
            "Species": "P. crino"
        },
        {
            "Common Name": "Beckers White",
            "Binomial Name": "Pontia beckerii",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Pieridae",
            "Genus": "Pontia",
            "Species": "P. beckerii"
        },
        {
            "Common Name": "Black Hairstreak",
            "Binomial Name": "Satyrium pruni",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Lycaenidae",
            "Genus": "Satyrium",
            "Species": "S. pruni"
        },
        {
            "Common Name": "Cabbage White",
            "Binomial Name": "Pieris rapae",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Pieridae",
            "Genus": "Pieris",
            "Species": "P. rapae"
        },
        {
            "Common Name": "Chestnut",
            "Binomial Name": "Polygonia c-album",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Nymphalidae",
            "Genus": "Polygonia",
            "Species": "P. c-album"
        },
        {
            "Common Name": "Clodius Parnassian",
            "Binomial Name": "Parnassius clodius",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Papilionidae",
            "Genus": "Parnassius",
            "Species": "P. clodius"
        },
        {
            "Common Name": "Clouded Sulphur",
            "Binomial Name": "Colias philodice",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Pieridae",
            "Genus": "Colias",
            "Species": "C. philodice"
        },
        {
            "Common Name": "Copper Tail",
            "Binomial Name": "Lycaena phlaeas",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Lycaenidae",
            "Genus": "Lycaena",
            "Species": "L. phlaeas"
        },
        {
            "Common Name": "Crescent",
            "Binomial Name": "Phyciodes tharos",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Nymphalidae",
            "Genus": "Phyciodes",
            "Species": "P. tharos"
        },
        {
            "Common Name": "Crimson Patch",
            "Binomial Name": "Chlosyne janais",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Nymphalidae",
            "Genus": "Chlosyne",
            "Species": "C. janais"
        },
        {
            "Common Name": "Eastern Comma",
            "Binomial Name": "Polygonia comma",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Nymphalidae",
            "Genus": "Polygonia",
            "Species": "P. comma"
        },
        {
            "Common Name": "Gold Banded Butterfly",
            "Binomial Name": "Baeotus baeotus",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Nymphalidae",
            "Genus": "Baeotus",
            "Species": "B. baeotus"
        },
        {
            "Common Name": "Great Eggfly",
            "Binomial Name": "Hypolimnas bolina",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Nymphalidae",
            "Genus": "Hypolimnas",
            "Species": "H. bolina"
        },
        {
            "Common Name": "Grey Hairstreak",
            "Binomial Name": "Strymon melinus",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Lycaenidae",
            "Genus": "Strymon",
            "Species": "S. melinus"
        },
        {
            "Common Name": "Indra Swallowtail",
            "Binomial Name": "Papilio indra",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Papilionidae",
            "Genus": "Papilio",
            "Species": "P. indra"
        },
        {
            "Common Name": "Julia",
            "Binomial Name": "Dryas iulia",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Nymphalidae",
            "Genus": "Dryas",
            "Species": "D. iulia"
        },
        {
            "Common Name": "Large Marble",
            "Binomial Name": "Euchloe ausonides",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Pieridae",
            "Genus": "Euchloe",
            "Species": "E. ausonides"
        },
        {
            "Common Name": "Malachite",
            "Binomial Name": "Siproeta stelenes",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Nymphalidae",
            "Genus": "Siproeta",
            "Species": "S. stelenes"
        },
        {
            "Common Name": "Mangrove Skipper",
            "Binomial Name": "Phocides pigmalion",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Hesperiidae",
            "Genus": "Phocides",
            "Species": "P. pigmalion"
        },
        {
            "Common Name": "Metalmark",
            "Binomial Name": "Apodemia mormo",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Riodinidae",
            "Genus": "Apodemia",
            "Species": "A. mormo"
        },
        {
            "Common Name": "Monarch",
            "Binomial Name": "Danaus plexippus",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Nymphalidae",
            "Genus": "Danaus",
            "Species": "D. plexippus"
        },
        {
            "Common Name": "Mourning Cloak",
            "Binomial Name": "Nymphalis antiopa",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Nymphalidae",
            "Genus": "Nymphalis",
            "Species": "N. antiopa"
        },
        {
            "Common Name": "Orange Oakleaf",
            "Binomial Name": "Kallima inachus",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Nymphalidae",
            "Genus": "Kallima",
            "Species": "K. inachus"
        },
        {
            "Common Name": "Orange Tip",
            "Binomial Name": "Anthocharis cardamines",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Pieridae",
            "Genus": "Anthocharis",
            "Species": "A. cardamines"
        },
        {
            "Common Name": "Orchard Swallowtail",
            "Binomial Name": "Papilio aegeus",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Papilionidae",
            "Genus": "Papilio",
            "Species": "P. aegeus"
        },
        {
            "Common Name": "Painted Lady",
            "Binomial Name": "Vanessa cardui",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Nymphalidae",
            "Genus": "Vanessa",
            "Species": "V. cardui"
        },
        {
            "Common Name": "Paper Kite",
            "Binomial Name": "Idea leuconoe",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Nymphalidae",
            "Genus": "Idea",
            "Species": "I. leuconoe"
        },
        {
            "Common Name": "Peacock Butterfly",
            "Binomial Name": "Aglais io",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Nymphalidae",
            "Genus": "Aglais",
            "Species": "A. io"
        },
        {
            "Common Name": "Pine White",
            "Binomial Name": "Neophasia menapia",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Pieridae",
            "Genus": "Neophasia",
            "Species": "N. menapia"
        },
        {
            "Common Name": "Pipevine Swallowtail",
            "Binomial Name": "Battus philenor",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Papilionidae",
            "Genus": "Battus",
            "Species": "B. philenor"
        },
        {
            "Common Name": "Purple Hairstreak",
            "Binomial Name": "Favonius quercus",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Lycaenidae",
            "Genus": "Favonius",
            "Species": "F. quercus"
        },
        {
            "Common Name": "Question Mark Butterfly",
            "Binomial Name": "Polygonia interrogationis",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Nymphalidae",
            "Genus": "Polygonia",
            "Species": "P. interrogationis"
        },
        {
            "Common Name": "Red Admiral",
            "Binomial Name": "Vanessa atalanta",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Nymphalidae",
            "Genus": "Vanessa",
            "Species": "V. atalanta"
        },
        {
            "Common Name": "Red Spotted Purple",
            "Binomial Name": "Limenitis arthemis",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Nymphalidae",
            "Genus": "Limenitis",
            "Species": "L. arthemis"
        },
        {
            "Common Name": "Scarce Swallowtail",
            "Binomial Name": "Iphiclides podalirius",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Papilionidae",
            "Genus": "Iphiclides",
            "Species": "I. podalirius"
        },
        {
            "Common Name": "Silver Spot Skipper",
            "Binomial Name": "Hesperia comma",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Hesperiidae",
            "Genus": "Hesperia",
            "Species": "H. comma"
        },
        {
            "Common Name": "Six-spot Burnet",
            "Binomial Name": "Zygaena filipendulae",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Zygaenidae",
            "Genus": "Zygaena",
            "Species": "Z. filipendulae"
        },
        {
            "Common Name": "Skipper",
            "Binomial Name": "Thymelicus sylvestris",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Hesperiidae",
            "Genus": "Thymelicus",
            "Species": "T. sylvestris"
        },
        {
            "Common Name": "Sootywing",
            "Binomial Name": "Pholisora catullus",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Hesperiidae",
            "Genus": "Pholisora",
            "Species": "P. catullus"
        },
        {
            "Common Name": "Southern Dogface",
            "Binomial Name": "Zerene cesonia",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Pieridae",
            "Genus": "Zerene",
            "Species": "Z. cesonia"
        },
        {
            "Common Name": "Striated Queen",
            "Binomial Name": "Danaus chrysippus",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Nymphalidae",
            "Genus": "Danaus",
            "Species": "D. chrysippus"
        },
        {
            "Common Name": "Two-barred Flasher",
            "Binomial Name": "Astraptes fulgerator",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Hesperiidae",
            "Genus": "Astraptes",
            "Species": "A. fulgerator"
        },
        {
            "Common Name": "Ulysses",
            "Binomial Name": "Papilio ulysses",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Papilionidae",
            "Genus": "Papilio",
            "Species": "P. ulysses"
        },
        {
            "Common Name": "Viceroy",
            "Binomial Name": "Limenitis archippus",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Nymphalidae",
            "Genus": "Limenitis",
            "Species": "L. archippus"
        },
        {
            "Common Name": "Wood Satyr",
            "Binomial Name": "Megisto cymela",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Nymphalidae",
            "Genus": "Megisto",
            "Species": "M. cymela"
        },
        {
            "Common Name": "Yellow Swallowtail",
            "Binomial Name": "Papilio machaon",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Papilionidae",
            "Genus": "Papilio",
            "Species": "P. machaon"
        },
        {
            "Common Name": "Zebra Longwing",
            "Binomial Name": "Heliconius charithonia",
            "Domain": "Eukarya",
            "Kingdom": "Animalia",
            "Phylum": "Arthropoda",
            "Class": "Insecta",
            "Order": "Lepidoptera",
            "Family": "Nymphalidae",
            "Genus": "Heliconius",
            "Species": "H. charithonia"
        }
    ]
